---
# tasks file for roles/ssh
- name: Add the SSH public key           
  authorized_key:
    user: ashifkey
    state: present
    manage_dir: yes
    key: "{{ lookup('file', 'roles/ssh/files/public_key.pub') }}"