---

#-----testing----
# - name: check url is reachable or not
#   uri:
#    url: "{{ url }}"
# - name: print the {{ url }} is working
#   debug:
#    msg: "{{ url }} is working and reachble"
#-----testing----


- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: install web components
  apt: name={{item}} state=present update_cache=yes 
  with_items:
    - fail2ban
    - vim
    - git