---
- name: Playbook to deploy to nginx server
  hosts: all
  become: yes
  roles:
   - role: roles/setup
     tags: setup
     
   - role: roles/nginx
     tags: nginx

   - role: roles/app
     tags: app

   - role: roles/ssh
     tags: ssh


