name: Deploy with Ansible

# on:
#   pull_request:
#     branches:
#       - main
#     types: [closed]

on:
  push:
    branches: ["main"]

# this comment added just to simulate a feature change from main branch

jobs:
  deploy:
    name: Deploy Ansible Playbook
    # if: github.event.pull_request.merged == true
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          
      # - name: Install Ansible
      #   shell: bash
      #   run: |
      #     sudo apt update
      #     sudo apt install -y ansible

      - name: Run Ansible Playbook
        env:
          ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}
          ANSIBLE_HOST_KEY_CHECKING: False
        run: |
          ansible-playbook node-playbook.yml --private-key private_key.pem -u ${{ secrets.ANSIBLE_USER }}